---
# yamllint disable rule:line-length
name: Fossa OSS PR scan

on:
  pull_request:
concurrency:
  group: ${{ github.event.repository.name }}-fossa-scanning-oss-${{ github.event.pull_request.number }}
  cancel-in-progress: true
jobs:
  fossa-native:
    runs-on:
      group: infra1-runners-arc
      labels: runners-small
    permissions:
      contents: read
      id-token: write
      pull-requests: write
    steps:
      - uses: gooddata/github-actions-public/fossa/pr-scan@master
        with:
          fossa-api-key: ${{ secrets.FOSSA_API_KEY }}
          npm-auth-token: ${{ secrets.NPM_TOKEN }}
          github-token: ${{ secrets.TOKEN_GITHUB_YENKINS }}
